
package brugerautorisation.transport.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BrugeradminImplService", targetNamespace = "http://soap.transport.brugerautorisation/", wsdlLocation = "http://javabog.dk:9901/brugeradmin?wsdl")
public class BrugeradminImplService
    extends Service
{

    private final static URL BRUGERADMINIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException BRUGERADMINIMPLSERVICE_EXCEPTION;
    private final static QName BRUGERADMINIMPLSERVICE_QNAME = new QName("http://soap.transport.brugerautorisation/", "BrugeradminImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://javabog.dk:9901/brugeradmin?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BRUGERADMINIMPLSERVICE_WSDL_LOCATION = url;
        BRUGERADMINIMPLSERVICE_EXCEPTION = e;
    }

    public BrugeradminImplService() {
        super(__getWsdlLocation(), BRUGERADMINIMPLSERVICE_QNAME);
    }

    public BrugeradminImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BRUGERADMINIMPLSERVICE_QNAME, features);
    }

    public BrugeradminImplService(URL wsdlLocation) {
        super(wsdlLocation, BRUGERADMINIMPLSERVICE_QNAME);
    }

    public BrugeradminImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BRUGERADMINIMPLSERVICE_QNAME, features);
    }

    public BrugeradminImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BrugeradminImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Brugeradmin
     */
    @WebEndpoint(name = "BrugeradminImplPort")
    public Brugeradmin getBrugeradminImplPort() {
        return super.getPort(new QName("http://soap.transport.brugerautorisation/", "BrugeradminImplPort"), Brugeradmin.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Brugeradmin
     */
    @WebEndpoint(name = "BrugeradminImplPort")
    public Brugeradmin getBrugeradminImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.transport.brugerautorisation/", "BrugeradminImplPort"), Brugeradmin.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BRUGERADMINIMPLSERVICE_EXCEPTION!= null) {
            throw BRUGERADMINIMPLSERVICE_EXCEPTION;
        }
        return BRUGERADMINIMPLSERVICE_WSDL_LOCATION;
    }

}
